  # key? 32byte (256bit)
jwt:
  secretKey: 12345678901234567890123456789012
  refreshKey: 12345678901234567890123456789012

logging:
  level:
    root: INFO
  file:
    name: logs/app.log  # logs 폴더에 app.log 파일 생성
    path: /logs



spring:
  mail:
    host: smtp.naver.com
    port: 465
    username: ${NAVER_MAIL_USERNAME}
    password: ${NAVER_MAIL_PASSWORD}
    protocol: smtp
    tls: true
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: false
          ssl:
            enable: true

  datasource:
    url: jdbc:mysql://127.0.0.1:3307/exampledb?useUnicode=true&serverTimezone=Asia/Seoul
    username: urstory
    password: u1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  batch:
    job:
      enabled: false
    initialize-schema: never
  main:
    allow-bean-definition-overriding: true
  task:
    scheduling:
      pool:
        size: 10