  # key? 32byte (256bit)
jwt:
  secretKey: 12345678901234567890123456789012
  refreshKey: 12345678901234567890123456789012

logging:
  level:
    root: INFO
  file:
    name: logs/app.log  # logs 폴더에 app.log 파일 생성
    path: /logs



spring:
  mail:
    host: smtp.naver.com
    port: 465
    username: ${NAVER_MAIL_USERNAME}
    password: ${NAVER_MAIL_PASSWORD}
    protocol: smtp
    tls: true
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: false
          ssl:
            enable: true

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  datasource:
    url: ${AUTUMN_DB_URL}
    username: ${AUTUMN_DB_USERNAME}
    password: ${AUTUMN_DB_PASSWORD}
    hikari:
      pool-name: HikariPool    # 풀 이름 지정 (로그 확인용)
      minimum-idle: 5  # 최소 커넥션 수
      maximum-pool-size: 20  # 최대 커넥션 수
      idle-timeout: 30000  # 커넥션 풀에서 커넥션이 유휴 상태로 있을 수 있는 시간 (밀리초)
      max-lifetime: 600000  # 커넥션의 최대 생명 주기 (밀리초)
      connection-timeout: 30000  # 커넥션을 얻을 때 대기 시간 (밀리초)
      leak-detection-threshold: 2000  # 2초 이상 사용되는 커넥션 감지
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  batch:
    job:
      enabled: false
    initialize-schema: never
  main:
    allow-bean-definition-overriding: true
  task:
    scheduling:
      pool:
        size: 10
  redis:
    host: ${AUTUMN_REDIS_HOST}
    port: ${AUTUMN_REDIS_PORT}
    password: ${AUTUMN_REDIS_PASSWORD}

  servlet:
    multipart:
      enabled: true
      max-file-size: 3MB
      max-request-size: 3MB

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
  server:
    port: 8081  # Actuator가 실행될 포트