# key? 32byte (256bit)
jwt:
  secretKey: 12345678901234567890123456789012
  refreshKey: 12345678901234567890123456789012

logging:
  level:
    root: INFO
  file:
    name: logs/app.log  # logs 폴더에 app.log 파일 생성
    path: /logs


spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/exampledb?useUnicode=true&serverTimezone=Asia/Seoul
    username: urstory
    password: u1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  batch:
    job:
      enabled: false